[package]
name = "iobewi-esp-console"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "ESP console sink: writes a log record to the ESP console"

[features]
default = []
esp32c3 = ["dep:esp-println", "esp-println/esp32c3"]
esp32s3 = ["dep:esp-println", "esp-println/esp32s3"]

[dependencies]
esp-println = { version = "~0.18", default-features = false, features = ["auto"], optional = true }
log = "0.4"
