[workspace]
members = [
  "common/time/core",
  "common/net/http/server",
  "common/net/io",
  "common/net/http/client",
  "common/log/core",
  "arch/esp32/log/console",
  "common/log/config",
  "common/config/space",
  "common/fs/nvs",
  "common/net/wifi/core",
  "common/net/improv/serial",
  "common/net/improv/provisioning",
  "common/net/wifi/manager",
  "arch/esp32/net/wifi",
  "examples/config-manager",
  "examples/wifi-modes",
  "arch/esp32/fs/nvs",
  "arch/esp32/config/space",
  "arch/esp32/flash",
  "arch/esp32/flash/partitions",
]
default-members = [
  "common/log/core",
  "common/config/space",
  "common/fs/nvs",
  "common/net/wifi/core",
  "common/net/wifi/manager",
  "common/net/improv/serial",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/iobewi/rust-mcu-libs"
