[workspace]
members = [
  "common/config/space",
  "common/fs/nvs",
  "examples/config-manager",
  "arch/esp32/fs/nvs",
  "arch/esp32/config/space",
  "arch/esp32/flash",
  "arch/esp32/flash/partitions",
]
default-members = [
  "examples/config-manager",
  "common/config/space",
  "common/fs/nvs",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/iobewi/rust-mcu-libs"
