[package]
name = "example-wifi-modes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
autobins = false

[[bin]]
name = "wifi-sta"
path = "src/bin/sta.rs"
required-features = ["firmware"]

[[bin]]
name = "wifi-ap"
path = "src/bin/ap.rs"
required-features = ["firmware"]

[[bin]]
name = "wifi-apsta"
path = "src/bin/apsta.rs"
required-features = ["firmware"]

[features]
default = []
firmware = []
esp32c3 = ["firmware", "esp-hal/esp32c3", "esp-rtos/esp32c3", "esp-radio/esp32c3", "esp-alloc/esp32c3", "esp-bootloader-esp-idf/esp32c3", "iobewi-esp-wifi/esp32c3", "iobewi-esp-console/esp32c3"]
esp32s3 = ["firmware", "esp-hal/esp32s3", "esp-rtos/esp32s3", "esp-radio/esp32s3", "esp-alloc/esp32s3", "esp-bootloader-esp-idf/esp32s3", "iobewi-esp-wifi/esp32s3", "iobewi-esp-console/esp32s3"]

[dependencies]
iobewi-log = { path = "../../common/log/core" }
iobewi-esp-console = { path = "../../arch/esp32/log/console", default-features = false }
iobewi-wifi-core = { path = "../../common/net/wifi/core" }
iobewi-esp-wifi = { path = "../../arch/esp32/net/wifi" }
esp-hal = { version = "~1.2", default-features = false, features = ["rt", "unstable"] }
esp-rtos = { version = "=0.4.0", default-features = false, features = ["embassy", "esp-radio", "esp-alloc"] }
esp-radio = { version = "=1.0.0-beta.1", default-features = false, features = ["wifi", "unstable"] }
esp-alloc = { version = "~0.11", default-features = false, features = ["global-allocator", "compat"] }
esp-bootloader-esp-idf = { version = "~0.6", default-features = false }
embassy-executor = { version = "0.10.0", default-features = false }
embassy-net = { version = "0.9.1", default-features = false, features = ["dhcpv4", "medium-ethernet", "tcp"] }
embassy-time = { version = "0.5", default-features = false }
static_cell = "2.1"
