[package]
name = "iobewi-esp-config-space"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "ESP NVS adapter for IOBEWI ConfigSpace"
keywords = ["esp32", "configuration", "nvs", "embedded", "no-std"]
categories = ["embedded", "hardware-support", "no-std"]

[features]
default = []
esp32c3 = [
  "iobewi-esp-flash/esp32c3",
  "iobewi-esp-nvs/esp32c3",
  "iobewi-esp-partitions/esp32c3",
]
esp32s3 = [
  "iobewi-esp-flash/esp32s3",
  "iobewi-esp-nvs/esp32s3",
  "iobewi-esp-partitions/esp32s3",
]

[dependencies]
iobewi-config-space = { path = "../../config" }
iobewi-nvs-core = { path = "../core" }
iobewi-esp-flash = { path = "../../../drivers/flash/esp32" }
iobewi-esp-nvs = { path = "../esp32" }
esp-nvs = "0.5.0"
log = { version = "0.4.29", default-features = false }

iobewi-esp-partitions = { path = "../../../drivers/flash/partitions-esp32" }
embedded-storage = "0.3.1"
